<a href="https://colab.research.google.com/github/Dianaepikson/HypatiaAcademy/blob/master/15_3_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

array = np.random.randint(1,100,(7,7))
print(array)

array[0:3,0:4]

[[80 64 55 29 63 98 96]
 [61  5 70 42  4 17 73]
 [ 7 99 14 23 29 22 42]
 [84 86 90 85 78 84 35]
 [36 75 15 40 56 25 96]
 [85 43 93 23  3 17 81]
 [73 91 85 33 97 89 55]]


array([[80, 64, 55, 29],
       [61,  5, 70, 42],
       [ 7, 99, 14, 23]])